// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vshkxolihepiaynjvplu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzaGt4b2xpaGVwaWF5bmp2cGx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDEzODYsImV4cCI6MjA3MTI3NzM4Nn0.TCi8d33-kdmNYecafFGxrzXbpwXfuWudTt2HVbGVNUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});